apiVersion: v1
kind: Service
metadata:
  name: devops-test-majid
  labels:
    app: devops
spec:
  selector:
    app: devops-test
  ports:
  - port: 8083
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
